name: pokidex
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
  path: ^1.6.0
  dio: ^3.0.0
  equatable: ^1.2.3
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/pokiball.png
    - assets/back.png




